d={1:"Hello",2:"Rudraksh",3:"Dusad",4:{1:"Hello",2:"Sachin"}}
print(d)
print(type(d))
print(d[1])
print(d[4][2])
dis={}
dis["Name"]="Hello"
dis[2]="Shanker"
print(dis[2])
del(d[4])
print(d)
del(dis["Name"])
print(dis)
d1=d.copy()
print(d1)
d1.clear()
print(d1)
print(d.keys())
print(d.values())
d.update({1:"Hi"})
print(d)
